apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qleu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qleu
    app.kubernetes.io/part-of: tkrw-pr712-0075-0069-app
  name: devfile-sample-qleu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qleu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qleu
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-qleu@sha256:0afc9915df7c92c9939a1ef8fdf1f73f5c399984728f56dcf8d7a17791a92e6f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
